workflows:
  android_release:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.rakshakai.rakshakai"
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter --version
          flutter clean
          flutter pub get
      - name: Build APK (release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
